# 排程資料庫連線位置
MSSQL_DB_SETTING:
  drivername: mssql+pymssql
  username: juns_chen
  password: 1qaz2wsx
  host: 10.0.130.225
  port: 1433
  database: DataTeam

TEST_MSSQL_DB_SETTING:
  drivername: mssql+pymssql
  username: c8
  password: 1qaz2wsx
  host: 10.0.128.225
  port: 1433
  database: DataTeam